### PR TITLE
Fix memory leak in the completed/failed indexing task.

### LINKED ISSUE #139: [webapp] high number of tasks breaks the index page
Some possibles to fix it:

- Pagination
- Truncate number of tasks to show
- Only shows some of the tasks in this interface.

### PR DESCRIPTION
**Pull request by bastiao**
This PR avoids to keep all indexing tasks in memory.
The oldest not running tasks are cleaned, to guarantee a hooked memory cleaning process. 

Base is master, but planned to merge in dev as well.

Resolves #139.

### CODE REVIEW

File: dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java [hunk 1]
```diff
@@ -52,17 +54,38 @@ public static RunningIndexTasks getInstance() {
...
 	}
 
+
+	public boolean hookRemoveRunningTasks(){
+	    if (this.taskRunningList.size()>SOFT_MAX_RUNNINGTASKS){
+	        int removedTasks = 0 ;
+	        Iterator<String> iterator = this.taskRunningList.keySet().iterator();
+	        while(iterator.hasNext()&& removedTasks<NUMBER_RUNNINGTASKS_TO_CLEAN){
+	            String tId = iterator.next();
+                Task t =  this.taskRunningList.get(tId);
```
Comment (Enet4) [inline dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java:79]: Raw type.

```suggestion
                Task<?> t =  this.taskRunningList.get(tId);
```

File: dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java [hunk 2]
```diff
@@ -52,17 +54,38 @@ public static RunningIndexTasks getInstance() {
...
+                if (t.isCancelled() || t.isDone()){
+                    iterator.remove();
+                    removedTasks++;
+                }
+            }
+        }
+	    return true;
```
Comment (Enet4) [inline dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java:86]: The method always returns `true`. It should either provide additional information through the returned value (e.g. whether at least one task was removed) or just return `void`.

**Review by Enet4 — COMMENTED** [review]
The concrete effect of these changes are that, upon the addition of a new task, `N` cancelled or stopped tasks are synchronously deleted from the list of tasks whenever we have more than `M` of them. `(N, M)` are `(2_000, 50_000)` by default.

We can move on with this proposal, as the issues arriving from a large number of task descriptors sitting in memory need to be resolved. Still, interest should be kept towards the resolution of #146 and #302. 

- #146 An integrated and generic task execution service, with centralised awareness of the process allocated resources, instead of relying on independent task pools per plugin.
- #302 A full, searchable history of tasks, enabling better task auditing without custom logging configurations.

Also, minor code improvement suggestions follow.

File: dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java (hunk 2 above)
Comment (bastiao) [reply dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java:86]: Thanks for feedback @Enet4. I will address the minor issues. The code at `dev` branch is already formated by the plugin already, so it will be easier to merge.

Regarding the other issues, sure, we can kept them for newest versions of Dicoogle 3 or 4 . For now, we need to close this one, close the 3.0.0 and move forward :)

Comment (Enet4) [reply dicoogle/src/main/java/pt/ua/dicoogle/taskManager/RunningIndexTasks.java:86]: > The code at dev branch is already formated by the plugin already, so it will be easier to merge.

Ah right, the 2.X development branch does not have standardized code formatting. We can look into that later if it becomes a nuisance. :)

I say it's good to merge once the other minor concerns are resolved.
