### PR TITLE
Fixed "java.io.FileNotFoundException: roles.xml 

### LINKED ISSUE #265: Create roles.xml on startup if missing
A new Dicoogle deployment will print a stack trace because of a missing roles.xml, whereas other configuration files are automatically created. We should make Dicoogle create a barebones file instead.

Example roles.xml:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Roles>
  <Role name="pen" />
  <Role name="healthcare" />
</Roles>
```

### PR DESCRIPTION
**Pull request by rlebre**
Fixed exception on startup when there is not any file called "roles.xml" (fixes #265 )

### CODE REVIEW

**Comment by jorgeMFS** [comment]
Uau

Em 19/09/2017 18:59, "Rui Lebre" <notifications@github.com> escreveu:

File: dicoogle/src/main/java/pt/ua/dicoogle/server/users/RolesXML.java [hunk 1]
```diff
@@ -101,11 +101,17 @@ private String resolveAttrib( String attr, Attributes attribs, String defaultVal
...
     {
         roles.reset();
-        
-        try
-        {
 
-            FileInputStream fin = new FileInputStream("roles.xml");
+        FileInputStream fin;
+
+        try {
```
Comment (Enet4) [inline dicoogle/src/main/java/pt/ua/dicoogle/server/users/RolesXML.java]: I believe one could also have a single try statement and catch `FileNotFoundException` at the end, next to the other catch blocks. But this seems fine.
